apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - demo-python-agent-deployment.yaml
  - demo-python-agent-service.yaml

images:
  - name: ghcr.io/agent-field/agentfield-control-plane
    newName: agentfield-control-plane
    newTag: local

