{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentfield.postgres.fullname" . }}
  labels:
    {{- include "agentfield.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agentfield.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}

